server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # ================= DISCOVERY LOCATOR =================
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # ================= HTTP CLIENT CONFIG =================
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s

      # ================= DEFAULT FILTERS =================
      default-filters:
        - RemoveResponseHeader=Transfer-Encoding

      # ================= ROUTES =================
      routes:

        # -------- AUTH SERVICE --------
        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

        # -------- ORDER SERVICE --------
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        # üîê USER INTERNAL APIS (MUST COME FIRST)
        - id: user-internal
          uri: lb://user-service
          predicates:
            - Path=/users/internal/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Internal-Call, true

        # üîì USER PUBLIC APIS
        - id: user-public
          uri: lb://user-service
          predicates:
            - Path=/users/**

# ================= JWT CONFIG =================
jwt:
  secret: MyVeryStrongAndSuperLongSecretKeyForJWTGeneration2026!

# ================= EUREKA CONFIG =================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# ================= LOGGING =================
logging:
  level:
    root: INFO
    com.apigateway.security: DEBUG
    org.springframework.cloud.gateway: INFO

# ================= ACTUATOR =================
management:
  endpoints:
    web:
      exposure:
        include: health,info
